spring:
  application:
    name: beans-insight
  datasource:
    url: jdbc:clickhouse://${CLICKHOUSE_HOST:insight-clickhouse-svc}:8123/${CLICKHOUSE_USERNAME:default}
    password: ${CLICKHOUSE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: beans-loyalty-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

server:
  port: 8005

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      percentiles:
        all:
          - 0.5
          - 0.95
          - 0.99
      percentiles-histogram:
        http.server.requests: true
    tags:
      application: "beans-insight"
  prometheus:
    metrics:
      export:
        enabled: true
  endpoint:
    prometheus:
      access: unrestricted